dodaj info o 1pkt za zrobienie na prawdziwym obrazku.
popraw zadania o copy

# Lista 2

## Numpy podstawy

(9pkt + 3pkt)

Na liście znajduje się 9 zadań do wykonania w trakcie zajęć. Po rozwiązaniu zadania pokaż kod prowadzącemu i odpowiedz na **pytanie kontrolne** (są one podane przy każdym zadaniu) — wtedy przyznajemy punkt. Dodatkowo prześlij zadanie na platformie skos.

Jeśli w poleceniu nie jest wskazane użycie pętli `for` - nie korzystaj z niej.

Zadania dodatkowe są oznaczone ⭐️. To zadani o numerach 10 i 11. Dodatkowo moeżesz otrzymać 1pkt z puli punktów bonusowych jeśli wykonasz wszystkie poniższe zadania związane z obrazami na prawdziwym obrazku.

Kazde zadnanie warte jest 1pkt.

## 1. Analiza pikseli obrazu

**Kontekst:** W AI obrazy to tablice NumPy (np. `H×W×C`). Proste operacje na obrazach można robić wektorowo bez pętli.

**Polecenie**

* Utwórz przykładową tablicę 3×3 obrazu RGB zawierającą wartości 0–255.
* Zwiększ jasność o 10% — ale **nie przekraczaj 255** (`np.clip`).
* Pokaż wynik i typ danych.

**Podpowiedź**
Zwiększ jasność obrazu mnożąc każde pasmo RGB przez 110%. 

In [10]:
import numpy as np
np.random.seed(1)
A = np.random.randint(0, 256, (3, 3))

bright = np.clip((A * 1.1 ), 0, 255)

print("Oryginał:\n", A)
print("Po zwiększeniu jasności o 10%:\n", bright)

Oryginał:
 [[ 37 235 140]
 [ 72 255 137]
 [203 133  79]]
Po zwiększeniu jasności o 10%:
 [[ 40.7 255.  154. ]
 [ 79.2 255.  150.7]
 [223.3 146.3  86.9]]


## 2. Normalizacja danych wejściowych

**Kontekst:** Dane wejściowe do modeli zazwyczaj normujemy — albo do `[0,1]`, albo standaryzujemy do średniej 0 i odchylenia 1.

**Polecenie**

* Wygeneruj 1D tablicę 100 losowych liczb w przedziale `0..255`.
* Przeskaluj na `[0,1]`.
* Następnie stwórz znormalizowaną wersję z średnią 0 i odchyleniem 1 (standaryzacja).
* Nie używaj pętli.

**Pytanie kontrolne:** Co się stanie, gdy `std == 0`?
>`Odp:` Otrzymamy błąd dzielenia przez zero

In [12]:
import numpy as np

x = np.random.randint(0, 255, 100)

# skalowanie do [0,1]
x_scaled = x / 255

# standaryzacja: (x - mean)/std
mean = x.mean()
std = x.std()
x_standardized = (x / mean)/std

print("mean scaled:", x_scaled.mean())
print("mean standardized:", x_standardized.mean())
print("std standardized:", x_standardized.std())

mean scaled: 0.4992941176470589
mean standardized: 0.01332197293560846
std standardized: 0.007854225573358466


## 3. Wycinanie fragmentów danych

**Kontekst:** Często dzielimy długi sygnał na krótsze okna (np. do ekstrakcji cech).

**Polecenie**

* Stwórz 1D tablicę długości 1000 (np. `np.arange(1000)`).
* Podziel ją na 10 fragmentów po 100 elementów (`reshape`).
* Oblicz średnią każdego fragmentu (wektor 10-elementowy).

**Pytanie kontrolne:** Co policzymy jeśli obliczymy `axis=0`?

>`Odp`: Policzymy wtedy średnią dla każdego wiersza, więc otrzymalibyśmy 100 średnich


In [ ]:
import numpy as np

x = np.arange(1000)
chunks = x.reshape(10, 100)   # shape (10,100)
means = chunks.mean(axis=1)   # średnia wzdłuż kolumn -> 10 wartości

print("shape chunks:", chunks.shape)
print("means:", means)

shape chunks: (10, 100)
means: (100,)


## 4. Operacje wzdłuż osi

**Kontekst:** Przy normalizacjach i agregacjach często operujemy wzdłuż konkretnej osi.

**Polecenie**

* Utwórz `X = np.random.randint(0, 100, (5,4))`.
* Oblicz:

  * min każdego wiersza używając `X.min(...)`
  * max każdej kolumny używając `X.max(...)`
* Znormalizuj każdy wiersz tak, aby suma elementów w wierszu była równa 1. Sprawdź poprawność rozwiązania sumując wartości w każdym wierszu.

In [22]:
import numpy as np

X = np.random.randint(0, 100, (5,4))

row_mins = X.min(axis=0)
col_maxs = X.max(axis=1)

# normalizacja wierszy do sumy 1
row_sums = X.sum(axis=1, keepdims=True)  # shape (5,1) - jakiego parametru trzeba użyć?
X_norm = X / row_sums

print("X:\n", X)
print("row_mins:", row_mins)
print("col_maxs:", col_maxs)
print("X_norm (suma wiersza):", X_norm.sum(axis=1))

X:
 [[28 55 82 31]
 [28 94 74  8]
 [99 32  8 84]
 [77 50 79 41]
 [64 83 24 20]]
row_mins: [28 32  8  8]
col_maxs: [82 94 99 79 83]
X_norm (suma wiersza): [1. 1. 1. 1. 1.]


## 5. Analiza embeddingów słów

**Kontekst:** W NLP słowa reprezentujemy wektorami (embeddingi). Często chcemy średnią reprezentację zdania i podobieństwo kosinusowe.

**Polecenie**

* Stwórz macierz `E` o kształcie `(5,50)` — 5 embeddingów po 50 wymiarów (`np.random.randn`).
* Oblicz:

  * `mean_embedding` (średni wektor po wierszach)
  * macierz podobieństw kosinusowych między wszystkimi parami wektorów (5×5)

**Pytanie kontrolne:** Jak interpretujesz wartości w `cosine_sim` (zakres i znaczenie)?
>`Odp`: 
> - $1$:  Wektory są identyczne (maksymalne podobieństwo)
> - $0$:  Wektory są ortogonalne - brak podobieństwa
> - $-1$: Wektory są przeciwne (maksymalnie różne, mają przeciwne kierunki)
---

### Wskazówka

Zastanów się, jak można obliczyć **podobieństwo kosinusowe** dwóch wektorów `a` i `b`, jeśli wiesz, że:

$$
\cos(\theta) = \frac{a \cdot b}{|a| \cdot |b|}
$$

Spróbuj najpierw policzyć to dla jednej pary wektorów w NumPy,
używając `np.dot()` i `np.linalg.norm()`.

A następnie pomyśl:

* Jak znormalizować wszystkie wektory jednocześnie, żeby każdy miał długość 1?
* Jak wykorzystać mnożenie macierzy (`@`), żeby w jednym kroku dostać podobieństwa między wszystkimi parami wektorów (5×5)?

In [ ]:
import numpy as np

E = np.random.randn(5, 50)

# średni wektor (embedding zdania)
mean_embedding = E.mean(axis=0)

# normalizacja wektorów do długości 1
img1_norms = np.linalg.norm(E, axis=1, keepdims=True)
E_normalized = E / img1_norms

# macierz podobieństw kosinusowych = E_norm @ E_norm.T
cosine_sim = E_normalized @ E_normalized.T

print("mean_embedding shape:", mean_embedding.shape)
print("cosine_sim shape:", cosine_sim.shape)
print("cosine_sim (przykład):\n", cosine_sim)

mean_embedding shape: (50,)
cosine_sim shape: (5, 5)
cosine_sim (przykład):
 [[ 1.          0.17564344  0.17259598  0.02164049 -0.02983295]
 [ 0.17564344  1.          0.09461156 -0.01796724 -0.02548829]
 [ 0.17259598  0.09461156  1.          0.15738228  0.16242618]
 [ 0.02164049 -0.01796724  0.15738228  1.          0.07310699]
 [-0.02983295 -0.02548829  0.16242618  0.07310699  1.        ]]


## 6. Sklejanie sensorów — dane z pojazdu autonomicznego

**Kontekst:** Dane z różnych sensorów różnią się formatem — trzeba je połączyć w jedną macierz cech.

**Polecenie**

* Stwórz:

  ```python
  lidar = np.random.rand(100, 2)   # x,y # lidar - Light Detection and Ranging
  camera = np.random.rand(100, 1)  # jasność
  radar = np.random.rand(100, 1)   # prędkość
  ```
* Połącz je kolumnowo w macierz `X` o kształcie `(100,4)`.
* Podziel `X` na `train` (80%) i `test` (20%) (np. `np.array_split` lub indeksowanie).
* Oblicz średnią jasność i średnią prędkość dla obu zestawów.

**Pytanie kontrolne:** Dlaczego warto przetasować dane (shuffle) przed splitem w prawdziwym pipeline?
>`Odp:` robienie shuffle przed splitem jest ważne, ponieważ kiedy otrzymujemy dane z jakiś pomiarów, to tasując to pozbywamy się ukrytych zależności
np. kolejności czasowej 

In [27]:
import numpy as np

lidar = np.random.rand(100, 2)   # x,y
camera = np.random.rand(100, 1)  # jasność
radar = np.random.rand(100, 1)   # prędkość

X = np.concat([lidar, camera, radar], axis=1)
assert X.shape == (100, 4)

# split train/test (bez shuffle dla prostoty)
n_train = int(0.8 * X.shape[0])
train = X[:n_train]
test = X[n_train:]

# indeksy kolumn: camera -> 2, radar -> 3 (0-based)
mean_camera_train = train[:, 2].mean()
mean_radar_train = train[:, 3].mean()
mean_camera_test = test[:, 2].mean()
mean_radar_test = test[:, 3].mean()

print("X.shape:", X.shape)
print("train/test shapes:", train.shape, test.shape)
print("mean camera train/test:", mean_camera_train, mean_camera_test)
print("mean radar train/test:", mean_radar_train, mean_radar_test)

X.shape: (100, 4)
train/test shapes: (80, 4) (20, 4)
mean camera train/test: 0.5283298906027495 0.5668166281832862
mean radar train/test: 0.5046100440852835 0.391396380307968


## 7. NumPy vs. czysty Python

**Kontekst:** NumPy działa o wiele szybciej niż pętle Pythonowe dla operacji numerycznych. Tu wykorzystamy `np.linspace`.

**Polecenie**

* Stwórz `x = np.linspace(0, 1, 10_000_000)`.
* Oblicz `s = sin(x)**2 + cos(x)**2`:

  * a) w czystym Pythonie (pętla `for` i `math.sin`, `math.cos`)
  * b) w NumPy (`np.sin`, `np.cos` — wektoryzacja)
* Porównaj czasy wykonania (wskazane: `%timeit` w notebooku lub `time.time()`).

In [29]:
import numpy as np
import math
import time

# dane
x = np.linspace(0, 1, 10_000_000)

# NumPy version
t0 = time.time()
y_np = np.sin(x)**2 + np.cos(x)**2
t_np = time.time() - t0

# Python loop version (bardzo wolne; uruchamiaj ostrożnie; jak trwa dłuej ni 15s, to przerwij i zmniejsz przykład)
t0 = time.time()
s = 0.0
for xi in x:           
    s += math.sin(xi)**2 + math.cos(xi)**2
t_py = time.time() - t0

print(f"NumPy time: {t_np:.3f}s")
print(f"Pure Python loop time: {t_py:.3f}s")

NumPy time: 0.464s
Pure Python loop time: 4.681s


## 8. Copy, View

**Kontekst:** Podczas preprocessingu zespoły czasami pracują na tym samym obiekcie myśląc, że mają kopię — to prowadzi do skażenia danych.

**Polecenie**

* Stwórz `patients = np.random.randint(60, 120, (5, 4))`.
  * `doctors_view`, gdzie doktor będzie przeglądał tylko co drugi pomiar,
  * `research_copy`, czyli kopię patients.
* Lekarz przez pomyłkę wykona `doctors_view[:] = -1`.
* Sprawdź, czy `patients` się zmieniło i czy `research_copy` pozostało bez zmian. Wyjaśnij.

**Pytanie kontrolne:** W jaki sposób zabezpieczyć workflow, żeby przypadkowe zmiany nie wpływały na bazę danych?
> `Odp`: Stworzyć etap w pipline gdzie będziemy używali struktury, która bazowo będzie zwracała tylko kopię, czyli nie będziemy bezpośrednio operowali na oryginalnych danych tylko takich opakowanych w naszą strukturę

In [30]:
import numpy as np

patients = np.random.randint(60, 120, (5, 4))
doctors_view = patients[::2]  
research_copy = patients.copy()

print("przed zmiana:\n", patients)
doctors_view[:] = -1
print("po zmianie doctors_view:\n", patients)
print("research_copy (czy zmienione?):\n", research_copy)

# wykrywamy, które są view / copy
print("doctors_view.base is patients?", doctors_view.base is patients)
print("research_copy.base is patients?", research_copy.base is patients)

przed zmiana:
 [[119  94  63  60]
 [ 76  88 117 117]
 [ 60  69  86  96]
 [ 98  98  77  73]
 [102 113 111 112]]
po zmianie doctors_view:
 [[ -1  -1  -1  -1]
 [ 76  88 117 117]
 [ -1  -1  -1  -1]
 [ 98  98  77  73]
 [ -1  -1  -1  -1]]
research_copy (czy zmienione?):
 [[119  94  63  60]
 [ 76  88 117 117]
 [ 60  69  86  96]
 [ 98  98  77  73]
 [102 113 111 112]]
doctors_view.base is patients? True
research_copy.base is patients? False


## 9. Jak CNN „przesuwa okno” po obrazie?

**Kontekst:** W konwolucyjnej sieci neuronowej filtr (np. 3×3) „przesuwa się” po obrazie piksel po pikselu. Parametr stride określa, o ile pikseli filtr przesuwa się w pamięci między kolejnymi pozycjami. Zrozumienie, jak numpy.strides działa, pozwala intuicyjnie pojąć, dlaczego operacja konwolucji może być wydajna bez kopiowania danych.

**Polecenie**

1. Utwórz: `A = np.arange(1,13).reshape(3,4)` — traktuj jako obraz `3 × 4`, oraz `AT = A.T`.
2. Wypisz: `A`, `A.strides`, `AT`, `AT.strides`.
3. Oblicz ile bajtów trzeba przeskoczyć, aby dotrzeć:
   * od `A[0,0]` do `A[0,1]`,
   * od `A[0,0]` do `A[1,0]`.
4. Sprawdź, czy `AT` jest widokiem (`AT.base is A`), zmień `A[0,0] = -99` i sprawdź `AT`.
5. Napisz funkcję `memory_offset(A, i, j)`, która obliczy ile bajtów trzeba przejść od `A[0][0]` do miejsca `A[i][j]`
   Użyj jej, żeby policzyć offsety kilku elementów w `A` i `A.T`. Zinterpretuj wyniki.

**Pytanie kontrolne:** Wyjaśnij własnymi słowami: co się stanie jak zmienisz `strides`?
>`Odp`: Różne modele po przez złe informacje o przechodzeniu między elementami mogą nauczyć się błędych danych - nie związanych z oryginalnymi

In [15]:
import numpy as np

A = np.arange(1, 13).reshape(3, 4)
print("A:\n", A)
print("A.strides:", A.strides) 

AT = A.T
print("AT:\n", AT)
print("AT.strides:", AT.strides)

# elementsize (liczba bajtów na element)
bs = AT.itemsize
print("itemsize (bajtów per element):", bs)

# obliczenia ręczne:
offset_A_00_to_01 = A.strides[0] * 0 + A.strides[1] * 1
offset_A_00_to_10 = A.strides[0] * 1 + A.strides[1] * 0
print("offset A[0,0] -> A[0,1] (bajtów):", offset_A_00_to_01)
print("offset A[0,0] -> A[1,0] (bajtów):", offset_A_00_to_10)

# sprawdzenie widoku
print("A.T.base is A ?", AT.base is A)

# zmiana A i obserwacja AT
A[0,0] = -99
print("A po zmianie:\n", A)
print("A.T po zmianie:\n", AT)

# funkcja memory_offset
def memory_offset(M, i, j):
    return M.strides[0] * i + M.strides[1] * j

print("memory offset A[2,3]:", memory_offset(A, 2, 3))
print("memory offset AT[2,3]:", memory_offset(AT, 2, 3))

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A.strides: (32, 8)
AT:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
AT.strides: (8, 32)
itemsize (bajtów per element): 8
offset A[0,0] -> A[0,1] (bajtów): 8
offset A[0,0] -> A[1,0] (bajtów): 32
A.T.base is A ? False
A po zmianie:
 [[-99   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
A.T po zmianie:
 [[-99   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4   8  12]]
memory offset A[2,3]: 88
memory offset AT[2,3]: 112


## 10. ⭐️ Zaawansowana augmentacja i analiza obrazów RGB

**Kontekst:** Przy trenowaniu CNN operujemy na obrazach RGB. Często robimy augmentacje (jasność, kontrast, rotacje, przesunięcia) i porównujemy obrazy np. za pomocą **cosine similarity**. Trzeba uważać, które operacje zwracają **widok**, a które **kopię**, aby nie psuć danych przez przypadek.

**Polecenie**

1. Wygeneruj **10 losowych obrazów RGB**, każdy o wymiarach `32×32×3` z wartościami `uint8` (0–255).
2. Napisz funkcję `cosine_similarity(img1, img2)`, która oblicza podobieństwo kosinusowe między dwoma obrazami traktowanymi jako wektory.
3. Stwórz funkcję `augment(img)` która tworzy warianty obrazu:

   * oryginał,
   * flip poziomy,
   * flip pionowy,
   * rotacja 90°,
   * jaśniejsza wersja,
   * wersja z większym kontrastem,
   * mały przesunięty fragment (crop + pad),
   * zamiana kanałów RGB na BGR.
4. Dla każdego wariantu sprawdź, które są **widokiem**, a które **kopią** (`.base`).
5. Oblicz macierz podobieństwa kosinusowego między wszystkimi 10 obrazami oryginalnymi i wypisz średnie podobieństwo.
6. Oblicz podobieństwo między oryginałami a ich wariantami i sprawdź, które operacje najbardziej zmieniają obraz (najmniejsze cosine similarity).   

In [ ]:
import numpy as np
x = np.random.randint(0, 256, (10, 32, 32, 3))
len(x)

10

In [21]:
def cosine_similarity(img1, img2):
    img1_1D = img1.ravel()
    img2_1D = img2.ravel()
    
    cosine_sim = img1_1D @ img2_1D.T / (np.linalg.norm(img1_1D) * (np.linalg.norm(img2_1D)))
    return cosine_sim

In [ ]:
dupa = np.random.randn(3, 2)
print(dupa)
flipped = np.fliplr(dupa)
print(flipped)
print(dupa)

def augment(img):
    flipped_h = np.fliplr(img)
    flipped_v = np.flipud(img)
    rotted90 = np.rot90(img)
    brigther = np.clip((img * 1.1), 0, 255)
    
    

[[-0.41583161 -0.59219013]
 [ 1.05363193 -0.59008907]
 [ 1.07171871  1.03892239]]
[[-0.59219013 -0.41583161]
 [-0.59008907  1.05363193]
 [ 1.03892239  1.07171871]]
[[-0.41583161 -0.59219013]
 [ 1.05363193 -0.59008907]
 [ 1.07171871  1.03892239]]


## 11. ⭐️ Świadome kopiowanie

**Kontekst**
Pracujesz z dużymi macierzami w Pythonie/NumPy, które reprezentują np. wyniki eksperymentów, symulacje lub dane użytkowników.

**Polecenie**
Twoim zadaniem jest zdecydować w jaki sposób należy **modyfikować dane**, w miejscu, w kopii, czy wystarczy widok? A może trzeba użyć deepcopy? Rozważ dwa przypadki - kiedy używasz biblioteki `numpy` i `copy`. Odpowiedz na wszystkie pytania. W każdej części musisz **uzasadnić wybór metody**.

Na początku stwórz dwuwymiarową tablicę `M`, na której będziesz demonstrować i uzasadniać użycie wybranej metody.

#### **a) Lokalna korekta**

Wartość w komórce `[0,0]` jest błędna i powinna być `1`.

* Jak poprawisz tę wartość?
* Czy zmieniasz oryginał, czy tworzysz kopię?
* Jak działa pamięć w tym przypadku?

#### **b) Alternatywna wersja danych**

Chcesz stworzyć **zmodyfikowaną wersję danych**, np. w kolumnie 2 przeskalować wszystkie wartości, w celu przeprowadzenia eksperymentu.

* Zastanów się, czy potrzebujesz `view`, `copy` czy `deepcopy`.
* Przetestuj różne podejścia (`M.view()`, `M.copy()`) i sprawdź, co się dzieje po modyfikacji nowej macierzy.

#### **c) Symulacje z listą zagnieżdżoną**

Tworzysz listę eksperymentów:

```python
L = [M, M.copy()]
```

Teraz chcesz **przeprowadzić symulacje zmian**, np. dodając losowe wartości, **bez zmiany oryginału** ani kopii w `L`.

* Jakiego rodzaju kopiowania użyjesz?
* Co się stanie, jeśli użyjesz tylko `copy` zamiast `deepcopy`, gdy struktura jest zagnieżdżona?

#### **d) Podzbiór kolumn**

Wybierasz podzbiór kolumn np. 1 i 3:

```python
subset = M[:, [1, 3]]
```

* Sprawdź, czy zmiany w `subset` wpływają na `M`.
* Porównaj to z cięciem typu `subset = M[:, 1:3]`.